### ISSUE TITLE
Error messages don't show on initial sign-up

### ISSUE THREAD

**Issue by WillTinney** [JulienPageaud/mobile-data-scoring-app#210]

**Comment by i-nomads** [comment]
Hey Will, can you describe?

**Comment by cdimitroulas** [comment]
@i-nomads, I have added client-side validation on the initial sign-up modal for the password length and password confirmation matching. Currently the only issue is if a user enters a mobile number which already exists in the database then the page is reloaded but no error message is shown

**Comment by i-nomads** [comment]
Ok I'll take care of that

**Comment by JulienPageaud** [comment]
Thanks Cyrille
