### ISSUE TITLE
Bug [MEDIUM] : incorrect email content when asking password reset

### ISSUE THREAD

**Issue by mzaradzki** [JulienPageaud/mobile-data-scoring-app#290]
Usage : ask for password reset
Bug : I received a reset email however this email states that my email has changed instead of providing new password

remark : the good thing is that the email did not go to spam

**Comment by cdimitroulas** [comment]
password reset feature has not been implemented. This was automatically generated when we were building the app.
This feature will need to be created for real if we need it as it is more complicated in our case where users may not have an email address as this is not a required field at the moment.

**Comment by i-nomads** [comment]
Who takes this decision?
Should we leave it out for now? Or should we give the user the option to enter an email OR mobile number, and therefore reset by email OR SMS?

**Comment by mzaradzki** [comment]
All users have mobile phone number and **many** of them will have an email address

Logic should be as follow :
a) if user has an email address, send an email and tell user an email has been sent to him
b) if user ONLY has mobile phone send a text [assuming we can do this]

@JulienPageaud : adding you to ticket

**Comment by JulienPageaud** [comment]
You are right Mat. Let's implement your logic here.

**Comment by JulienPageaud** [comment]
Hey @i-nomads , can you please fix that?

**Comment by i-nomads** [comment]
I'm on it

**Comment by i-nomads** [comment]
Email is done, will do SMS ASAP

**Comment by JulienPageaud** [comment]
Many thanks Cyrille
