### ISSUE TITLE
Bug [HIGH] : error when filling profile from Facebook page

### ISSUE THREAD

**Issue by mzaradzki** [JulienPageaud/mobile-data-scoring-app#296]
Facebook indicates a URL error

**Comment by WillTinney** [comment]
I've added a solution which takes the data pulled from facebook and renders the edit form with the applicable fields filled in rather than explicitly "connecting" the facebook account - atm the only fields we can get from facebook without applying for more are email, first name, and last name

**Comment by mzaradzki** [comment]
Can we also get the number of friends (even if we dont have the list of friends) ?
I managed to get it without waiting for validation from Facebook but a game I wrote.
This would be useful information if we can have it easily.

**Comment by cdimitroulas** [comment]
This bug has been fixed, we can look into adding the number of friends to the require fields
@mzaradzki maybe we should make that a separate issue and close this one?

**Comment by mzaradzki** [comment]
Here is the new issue for the friend count : 
https://github.com/JulienPageaud/mobile-data-scoring-app/issues/323
