### ISSUE TITLE
Bug [HIGH] : short password in signup (new users) not signaled properly

### ISSUE THREAD

**Issue by mzaradzki** [JulienPageaud/mobile-data-scoring-app#297]
Usage : new user click on signup and fill in phone number and password
Bug : the password needs to be valid (minimum length for example) but if you type a short one like "aaaa" and click send you just get a new modal popup form with no clear explanation as for what happened

**Comment by cdimitroulas** [comment]
I will add a client-side validation to prevent the form submission on a short password to prevent this problem

**Comment by mzaradzki** [comment]
when the password is not valid a clear feedback like "password too short" should be displayed
OR the placeholder could state upfront "please use at least 8 characters, letter or digits only ..."
